# Generated by Django 4.1 on 2023-01-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0004_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='meeting_app.topic'),
        ),
    ]
